logging:
  mode: offline
  project: Cell-Segmentation
  notes: CellViT-256
  log_comment: CellViT-256-Fold-1
  tags:
  - Fold-0
  - ViT256
  - 40x
  wandb_dir: /scratch/nmoreau/CellViT_2025/results_cellvit/
  log_dir: /scratch/nmoreau/CellViT_2025/results_cellvit/log/
  level: Debug
  group: CellViT256
random_seed: 19
gpu: 0
data:
  dataset: conic
  dataset_path: /scratch/nmoreau/CellViT_2025/kidney_data_256_40x/
  magnification: 40
  train_folds:
  - 0
  val_folds:
  - 1
  test_folds:
  - 2
  num_nuclei_classes: 8
  num_tissue_classes: 1
model:
  backbone: ViT256
  pretrained_encoder: /scratch/nmoreau/CellViT_2025/checkpoints/vit256_small_dino.pth
  shared_skip_connections: true
loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 8

training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 16
  epochs: 130
  optimizer: AdamW
  early_stopping_patience: 130
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 25
  sampling_gamma: 0.85
  sampling_strategy: cell
  mixed_precision: true
transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  downscale:
    p: 0.15
    scale: 0.5
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.25
    var_limit: 50
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  randomsizedcrop:
    p: 0.1
  elastictransform:
    p: 0.2
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: latest_checkpoint.pth
run_sweep: false
agent: null
dataset_config:
  tissue_types:
    Colon: 0
  nuclei_types:
    Background: 0
    Opal_480: 1
    Opal_520: 2
    Opal_570: 3
    Opal_620: 4
    Opal_690: 5
    Outside: 6
    Unclassified: 7
